CODE_TO_ALTER_Spatial_BRP.dat
CODE_TO_ALTER_Spatial_BRP.tpl

In this update I have added functions that calculate a recruitment index (before movement). I have also written a function that calculates true catch-at-age proportions and observed catch-at-age proportions based on "true" catch-at-age and assuming those values are means of a log normal error distribution. The .dat file was updated to accommodate input of age-specific sigmas.

Updated CODE_TO_ALTER_Spatial_BRP

---

CODE_TO_ALTER_Spatial_BRP.dat
CODE_TO_ALTER_Spatial_BRP.tpl

In this update I have added a switch that allows for random allocation of recruitment to areas within populations. It assigns a uniform random deviate (0-1) to each region within years then sums across regions to calculate the proportion of the total recruitment that is assigned to each area. Calculations have been tested and code works. Another change is in by-passing the SPR calcs for the stock-recruitment relationship. The alpha and beta coefficients are now calculated from population steepness, R_ave and unfinished-equilibrium SSB (calculated from initial abundance at age). This, of course, assumes that the model is starting at unfished equilibrium...which might not always be the case...

Changes to vitals calcs

---

CODE_TO_ALTER_Spatial_BRP.dat
CODE_TO_ALTER_Spatial_BRP.tpl

Added ability to apportion input TAC or harvest rate based on observed survey or recruitment index.  Added a series of associated switches to NR calcs.  
Added ability to calc a recruit index before or after movement.
Fixed typo in survey calcs that caused model to crash.
Renamed overlap_switch to natal_homing_switch and separated it into two switches with a new spawn_return_switch.
Handful of minor aesthetic changes, updated commentary, etc...

Add switch for altering tac by obs data

---

CODE_TO_ALTER_Spatial_BRP.dat
CODE_TO_ALTER_Spatial_BRP.tpl

New switch to allow TAC to be calculated according to input_uMSY*biomass_total(y)*apportionment_factor
This allows a yearly TAC that corresponds to the total uMSY and can be apportioned based on any of the aforecoded (I made up a new word and I like it) apportionment schemes
I believe this is the only appropriate way to code apportioning of uMSY because if apportion uMSY directly, then will never attain the true total uMSY that are trying to achieve (because to do so would require fishing each region at uMSY)....you may achieve uMSY through luck if the true uMSY by region matches the applied u by region (but unlikely)
To apply this method you must input the uMSY (total) into each fleet in the input_u array, use model_type==1 (because calculating a TAC and actually fitting that in the NR …

Code to calculate TAC from input_uMSY(total)

---

Spatial_BRP_project/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat
Spatial_BRP_project/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl
Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat
Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl

Had to change the fleet setup.  The number of fleets (survey or fishery) are constant across regions in an given area/population (can still have different number of fleets by area/population and different fleet selectivity across regions within an area).

Fix 6d arrays

---

Spatial_BRP_project/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl
Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl

Added the ability to use the calc_TAC_from_uMSY switch when parse_TAC==0.  This allows checking whether the approach of TAC=uMSY*biomass results in the same stock trajectory as fishing at MSY (i.e., the base model MSY search runs). 
NOTE: If implementing this input the region specific uMSY (not the total uMSY).

Add check on u msy bio calc

---

Spatial_BRP_project/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat
Spatial_BRP_project/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl

2 files were changed to add in error for regional SSB indices  (CODE_TO_ALTER_Spatial_BRP.dat and CODE_TO_ALTER_Spatial_BRP.tpl) for spatial BRP operating model

added error to regional SSB indices

---

Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat
Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl

Added the tagging component to the simulation model.  I think I included all aspects that were discussed at the meeting.  I've tested this for 1 pop, 2 regions and 2 pops, 2 regs and everything looked good.  Note that I tried running the model with 2 pops and uneven regions per pop and I ran into some errors (before the tag function), so we probably want to avoid having different numbers of regions for each populations (I believe this is a problem with the ragged arrays, which may not be an easy fix).
We can input the number of years that we want tagging to occur along with the specific years of each tagging event (i.e., you input the total number of release events and the years that these events occur), so it is flexible for any number of tagging scenarios.  In addition, you input the …

Added simulated tagging data

---

Spatial_BRP_project/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl

Things added to SPASAM\Spatial_BRP_project\Operating_Model:
1.	Added report out of “nfleets_survey”
2.	5d and 6d arrays
Reorganized all 6d arrays that aren’t temporary: 
renamed variables to start with ‘ro’, and redefined so that the first two dimensions are population from and region, as opposed to population from and population to. For 6d vital arrays, dimensions were already population from and region, so did not need to reorganize. Outputted as 4d arrays indexed by the region number (region 1 = pop 1 region 1; region 2 = pop 1 region 2 (or pop 2 region 1 is single regions per pop; etc.) with naming convention of “_X” at the end where X is the region number, which required indexing over region and population (from) dimensions. 
Outputted all 5d arrays that aren’t temporary:
outputted …

Updated report out section

---

Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl

Updated so that all 5d+ arrays could  be read using R. 
Things added to SPASAM\Tag_integrated_model\Operating_Model:
1.	Added report out of “nfleets_survey”
2.	Removed extra report out of “nages”
3.	Remove report out of “tag_prop_final” and “OBS_tag_prop” since these are 5d arrays and I report them out with formatting described in point 5.
4.	Removed four more variables in the report section that would cause issues when reading in the report file because they were 5d arrays. These were true_survey_fleet_bio_overlap, OBS_survey_fleet_bio_overlap, yield_region_fleet_overlap, OBS_yield_region_fleet_overlap. These variable were included in point 5, below.  
5.	5d and 6d arrays
Reorganized all 6d arrays that aren’t temporary: 
renamed variables to start with ‘ro’, and redefined so that the …

Update the TIM OM tpl file into the master branch

---

Spatial_BRP_project/Operating_Model/Pop_TAC.dat
Spatial_BRP_project/Operating_Model/Pop_TAC.tpl

added parse_TAC_source==4 which uses an input apportionment factor, which is included after the input_u in the .dat file.  You can input any apportionment, but this is mostly used so can calculate the TAC using uMSY_pop*bio_pop and use the 'true' apportionment from MSY runs.  The result should get you back to MSY (by region and total).  Results from these runs demonstrate that apportionment must account for apportioning u and bio if it is to get back to MSY levels.  Only apportioning based on bio (ie survey values) cannot be expected to produce MSY without also apportioning the uMSY_pop separately.
**note that this model does not include the updated metapop calcs so probably won't work correctly if using metapop**

updated code to allow input apportionment

---

Tag_Integrated_Model/simple model/Model Runs/Plot.R

I added some additional features to JJD version of plot.R for looking at model output. I included a section that runs both OM and EM by automatically moving the .rep from the OM directory to EM directory, converts to .dat then runs EM. Seemed to work well in prelim tests.

Added features to plot.R

---

Tag_Integrated_Model/Estimation_Model/Mult Pops/TIM_EM.tpl
Tag_Integrated_Model/Estimation_Model/Mult Regs/TIM_EM.tpl
Tag_Integrated_Model/Estimation_Model/panmictic/TIM_EM.tpl

minor tweak to ensure that T is fixed at yearly (not age-specific) true value when movement estimation phases are negative.

Fix input T

---

Tag_Integrated_Model/Estimation_Model/TIM_EM.tpl

Added code to fix steepness at the average when running a panmictic EM with outputs from spatial OM and when phase for steepness is negative.

fix steepness at average for panmictic

---

Tag_Integrated_Model/Operating_Model/TIM_OM.dat
Tag_Integrated_Model/Operating_Model/TIM_OM.tpl

Updated the OM with diagnostics switch that allows true (without error) values for indices, age comps and tag proportion to be used in likelihoods.

Use true values in likelihood

---

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R

Added residual plots for tagging data. Prints out the model structures, if the OM/EM are matching or mismatching, if the model is a diagnostic run (uses true values) and generates a table of error parameters for the OM (similar table for the EM coming soon). This works only for matching but for all three population structures. Also reformatted plots to be nicer to review and on standard printing pages. 
Many items presented in tables are reading from the OM dat. Several small but important adjustment made to OM dat to run code successfully.

Add features to r_wrapper

---

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R

Now prints true and estimated recruitment apportionment. Also divides tag residuals into separate plots for each release area or region and creates a separate landscape PDF for tag residuals only.

added features to diagnostics wrapper

---

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R

when mismatch with panmictic EM, only produces a graph of OM apportionment only.

Fixed output for rec apport

---

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R

Further generalized code to handle any model name which is entered in the run set up. Code now recognizes selectivity configuration for fishery and survey (input, logistic, etc) and will only populate true and estimated parameter tables with parameters corresponding to set up (e.g. logistic only shows beta 1 and 2). Tidied up the tables so they are not overlapping. Adjusted font size. To work correctly, the OM .dat switch title needs to be select_switch_EM or select_switch_survey_EM. Might need to change that in whatever .dat is being used. I fixed it manually in the current OM .dat.

Few improvements to diagnostic wrapper

---

Tag_Integrated_Model/Estimation_Model/TIM_EM.tpl

Somehow overlooked fixing init_abund to true when setting it to a negative phase. All better now. Will not work for a mismatch to panmictic.

Fixed init_abund when phase is negative
