CODE_TO_ALTER_Spatial_BRP.dat, CODE_TO_ALTER_Spatial_BRP.tpl
Added function that allows annual recruitment to be determined as a sine wave function. Can input amplitude (% of average) and frequency (years)  into the .dat file. Still needs some work to carry through in abundance calcs.
=> more updates

CODE_TO_ALTER_Spatial_BRP.dat, CODE_TO_ALTER_Spatial_BRP.tpl
finished adding recruitment type 3 (Rec_Type==3). Recruitment is modeled in a separate function and carried though the abundance calcs. Tested and works except there is a bug in the calculations when apportion by SSB in each region. Need to work on that a bit more.
=> Updates to recruitment calcs

CODE_TO_ALTER_Spatial_BRP.dat, CODE_TO_ALTER_Spatial_BRP.tpl
Changed the terminology in the code from stock to population to better reflect what the model is simulating. Tested, debugged and works!
=> Changed "stock" to "population"

CODE_TO_ALTER_Spatial_BRP.dat, CODE_TO_ALTER_Spatial_BRP.tpl
I made changes to model to allow maturity to vary by area within populations. This involved increasing the dimensions of the maturity parameter. I created another variable that calculates the average maturity across all areas and uses the average for the SPR calculations - will probably need to fix that but the code is now functioning. I did a few tests on the calcs and it looks good but probably need more debug. Still need to add new params to report section.
=> Model now accepts maturity varying by area

CODE_TO_ALTER_Spatial_BRP.dat, CODE_TO_ALTER_Spatial_BRP.tpl
In this addition I have coded a true and observed survey index into the abundance calculations. The true index is spatially-explicit with regional varying selectivity and catchability and can accommodate multiple surveys (as fleets). The calculations summarize the index by population index and also provide regional age composition from the index. The observed survey index includes both observation and process error which is based on specified survey sigma and age-specific aging error. In preparation for manuscript 2, I have coded a matrix that provides the proportion of total abundance in each area in each year based on the survey index...this can be modified to include SSB or any other parameter that might be used to apportion harvest across areas...Again this example used HAKE …
=> more additions including survey index

MSY_Search_Panmictic.R
Also lumped the whole deal into a single function for quick and easy running.
=> Added parallel processing to panmictic MSY search

MSY_Search_Spatial.R
This code puts everything in a single function. The next step will be it iterate over folders for MSY search runs...coming soon.
=> Small edits to MSY_search_Spatial.R

CODE_TO_ALTER_Spatial_BRP.dat, CODE_TO_ALTER_Spatial_BRP.tpl
Included survey timing
Included timelags in catch apportionment based on surveys
Allow surveys to be calculated by natal population and area
Clean up observed survey calcs
=> Survey timing/pop specific

CODE_TO_ALTER_Spatial_BRP.dat, CODE_TO_ALTER_Spatial_BRP.tpl
Minor fixes to Aaron's code
Now works
Now I go watch the Miami Open and Drink Beer in the Sun
=> Fix apportionment

Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat, Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl
Now calcs true and obs age comps for both survey and catch data assuming multinomial distribution.
=> Added calculation of Observed Age comps

Spatial_BRP_project/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat, Spatial_BRP_project/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl, Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat, Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl
fix code to allow use of bio_pop or bio_reg when using uMSY*bio=TAC
=> allow use of reg_bio or pop_bio for TAC calc

Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat, Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl
Took a shot at adding random walk F.  Let me know if I'm using github as intended and if I did something remotely useful.
thanks,
JJD
=> Implement random walk f

Spatial_BRP_project/Operating_Model/Spatial_BRP.tpl
A fixed a small error that set Rec_type to 2 overwriting the .dat input and another fix to the rep file
=> Fixed a bug in the SPR Calculations

Tag_Integrated_Model/Estimation_Model/Tag_Estimation.tpl, Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat, Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl, Tag_Integrated_Model/Operating_Model/Faster/B.tpl
I have now also added the spr calcs changes to the tag integrated OM, Dana's "faster" tag integrated OM, and the tag integrated estimation model (which Dana has called Tag_Estimation.tpl).  I think that's all the places that the change(s) needs to be made.
=> Issue84 bratio rec type1 jjd

Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.dat, Tag_Integrated_Model/Operating_Model/CODE_TO_ALTER_Spatial_BRP.tpl
I fixed up the .dat file so there are no longer "nan" or inf in the natal homing calcs. Parameters are boring but they work for now for generating a fake data set.
=> new dat file

Tag_Integrated_Model/Estimation_Model/Tag_Estimation.tpl
removed OM specific code--NO MORE NEWTON-RAPHSON!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
cleaned up questions from J+D
added comments where additions still needed
=> cleaned up code

Tag_Integrated_Model/Operating_Model/TIM_OM/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM/TIM_OM.tpl
lots and lots and lots of ivectors
=> fix tag_age issue, i hope

Tag_Integrated_Model/Estimation_Model/tim_sab.tpl, Tag_Integrated_Model/Operating_Model/TIM_OM/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM/TIM_OM.tpl
fixed tagging proportions in OM and EM and added a switch to sim logistic survey selectivity
still need to add a minor tweak to tagging calcs in EM
=> Fix tag add survey sel switch

Tag_Integrated_Model/Estimation_Model/Mult Pops/TIM_EM.tpl, Tag_Integrated_Model/Estimation_Model/Mult Regs/TIM_EM.tpl, Tag_Integrated_Model/R_wrappers/TIM_Diagnostics.R
when phase is negative, uses input for q, steep, R_ave, rec_dev. I am not sure how to handle the first values in rec_dev vector as those are used for estimating init_devs...help?
=> Input true from OM

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics.R
Not sure what happened last time but take two...
=> mysterious non-uploading file re-do

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics.R
further updates to output and plots. Added yield and survey index model fits.
=> Added yield and survey plots

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics.R
Fixed a couple things to run panmictic OM/EM. Works!
=> minor adjustments

Tag_Integrated_Model/Estimation_Model/TIM_EM.tpl
Added pieces of Brian's code to print 5D arrays in .rep for pulling into R
=> prints 5D arrays by population

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_file_loops.R
Code is now generalized to handle panmictic, metamictic and metapopulation scenarios. Added functionality of looping through runs in a master directory to "set it and forget it". Additional recruitment outputs to .txt.
=> many more features to R wrapper

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
In the process of updating the report to output aggregated values for panmictic EM. This is not completed but is in progress. Changes have been made to the .dat and .tpl.
=> report output for mismatch

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
Adding some modifications of the .rep to report out the aggregated values for panmictic EM. It is a work in progress and does not yet work with the mismatch but works fine with the matching for coding EM.
=> Beginnings of updating .rep

Spatial_BRP_project/GreatDana_MSY_search/Improved_MSY_search.R
R code pulls terminal biomass at age from .rep and saves as .csv
=> output and save biomass at age

Spatial_BRP_project/GreatDana_MSY_search/GreatDana_MSY_search.tpl
Updated .rep to output biomass at age
=> Output biomass-age-age

Spatial_BRP_project/GreatDana_MSY_search/GreatDana_MSY_search.tpl, Spatial_BRP_project/GreatDana_MSY_search/Improved_MSY_search.R
Added outputs for area-specific abund at age
=> additional outputs in .rep

Spatial_BRP_project/MSY_Search_Spatial_edit.R
more area specific outputs in R code
=> updates to MSY grid search

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
Fused Dana's recent version of the OM with the partial mis-match code and matching metapop structure .dat. Seems to be working.
=> Merged GreatDana additions

Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
Calculate abundance fraction by age, pop/region for weighted averaging of panmictic EM outputs. Keeping files up-to-date.
=> calculate abundance fraction and more

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
Now can output abundance weighted or aggregated outputs from spatial OM to read into EM. Still needs a little work but getting there!!!
=> now have panmictic outputs for spatial OM

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
Updated outputs and fixed bug to run multi-pop, multi-area, and pan matching.
=> fixed bugs for multi-area

Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
Fixed panmictic outputs for matching if doing tagging calculations. What a pain in the neck!
=> bugs fixed for panmicitic matching

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Added residual plots for Recruitment, SSB, F, Selectivity, Movement and Initial Abundance. Residuals are presented as relative percent difference from true
=> TIM wrapper with residual plots added

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
fixed error in the calculation for RPD of estimated selectivity.
=> fixed error in selectivity residual plot

Tag_Integrated_Model/Operating_Model/TIM_OM.dat
=> keeping files up to date

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Added residual plots to TIM diagnostics code that show model fit to age compositions.
=> residual plot for age compositions

Tag_Integrated_Model/Estimation_Model/TIM_EM.tpl
Added age compositions to report for plotting.
=> added new outputs to report

Tag_Integrated_Model/Operating_Model/TIM_OM.dat
Several small but important adjustment made to OM .dat to run code successfully. This is a metapopulation example.
=> small changes for R wrapper

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
=> Fixed bad index on tag plot

Tag_Integrated_Model/Operating_Model/TIM_OM.dat
.dat file that works around the issues with age1 movement and init_abund so estimates in EM are unbiased
=> OM .dat that works without bias

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Fixed some issues with the output for 3 area models
=> Fixed some bugs

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Now allows the user to define how residuals are calculated. They can be presented as a straight difference or relative difference. Added residuals for fits to yield and survey.
=> New features to diagnostics wrapper

Tag_Integrated_Model/R_wrappers/SIM_TIM_editing.R
Fixed issue with directories. Added additional plots (biomass and F). Allows for user to choose colors at the beginning of the code. I think it works...?
=> Added more stuff

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Tidy the diagnostic code a bit and added Recruitment apportionment plots
=> added features to R wrapper

Tag_Integrated_Model/Estimation_Model/TIM_EM.tpl
Constrained some of the bounds on a few estimated parameters to stabilize estimation. Provide starting values for Rec_devs and abund_devs. This stuff was jumping all crazy like.  Not sure it really did anything but seems to have helped a little. Also increased the convergence criteria for running diagnostic runs.
=> added some constraints

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
This model seems to be the best we have so far. Added bounds for R_ave to be defined in OM .dat
=> Best we have so far

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
I added plots for rec deviations and fixed up a couple other plots.
=> Added rec devs and some other stuff

Tag_Integrated_Model/Estimation_Model/TIM_EM.dat, Tag_Integrated_Model/Estimation_Model/TIM_EM.tpl
Cleaning up some problems that I created earlier. Nice working EM for multi-area!
=> fixed a couple things

Tag_Integrated_Model/Estimation_Model/TIM_EM.tpl
This EM will run a panmictic assessment with a metamictic OM population structure. Two quirks...1) cannot yet do a diagnostic run (diagnostics_switch==1) and all parameters (with the exception of movement), need to be estimated because the TRUE outputs are at the OM dimensions. More refining will come later.
=> we have mismatch!!!

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
The updates to the wrapper allow plots for mismatch to panmictic from metamictic OM. Also runs all scenarios that are matching.
=> Updates to diagnostic code

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
=> Small fixes to outputs

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
Updates to the OM generate output for fleets as areas estimation model (which seems to work!)
=> generates output for fleets as areas

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
few updates to plot outputs for FAA mismatch with spatial OM.
=> some updates for FAA output

Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
=> change back to correct version

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Generates bar plot of likelihood components for the run and creates tables showing the values of the true and estimated parameters. Also provides a statement showing if the model converged.
=> new features to wrapper

Managment_Boundaries/R_wrappers/Sims_master.R, Managment_Boundaries/R_wrappers/TIM_Diagnostics_master.R
Fixed issue with the model name in both the sims code and the diagnostics code. Now specify the name of the model at the top of the code when setting up a run. No need to make changes elsewhere.
=> Improvements to wrappers

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Now diagnostics wrapper will show the max gradient on the first page of the diagnostic plot. This is read directly from the .par file in the EM folder. I have also added 2 tables at the back of the document, the parameter estimates on the log scale with standard errors (read from the .std) and a correlation table that highlights any correlations with an absolute value > 0.5.
=> More features to the wrapper

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Abandoned the table approach for the correlation matrix and instead, we now generate a pdf with a plot of the correlation matrix. User defines the threshold for showing correlated parameters. Also, a pdf is generated showing the .std table for quick reference.
=> correlation plot to wrapper

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Fixed an error for plotting the correlation matrix
=> Couple fixes to the wrapper

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Fixed problem with cor plot. Now removes old std and cor files prior to run.
=> updates to wrapper

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
new method to remove old EM .dat file.
=> remove old  EM .dat

Managment_Boundaries/Operating_Model/MB_OM.dat, Managment_Boundaries/Operating_Model/MB_OM.tpl
This is the best working OM we have as of now. Files updated.
=> Upgrade to new OM

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
updated OM with weights and penalties controlled from .dat. Init_abund now can be estimated from input values. Errors fixed in abundance calcs
=> Updates to OM

Tag_Integrated_Model/Operating_Model/TIM_OM.dat
This .dat works well for sablefish-like example
=> .dat that works

Tag_Integrated_Model/Operating_Model/TIM_OM.dat
Finally, a full estimation that works! Survey selectivity is squirrely so bounds are drawn in.
=> Better .dat

Tag_Integrated_Model/R_wrappers/SIM_TIM_editing.R, Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_SIM.R
TIM_diagnostics_SIM is the diagnostics code modified to be sourced from SIMS wrapper to generate diagnostics pdf.  SIM_TIM_editing is the current version of the full sims wrapper. This code will run a user-defined number of sims, save and organize the report files and pull important outputs for plotting and summary stats. A number of summary files are generated reporting bias and features of the run. Some plots are also generated. This has been built using only the matching OM/EM so probably more work will be needed for the mismatch.
=> TIM wrappers needed to run simulations

Tag_Integrated_Model/R_wrappers/SIM_TIM_editing.R
Fixed some bugs and added new plots. R_ave, q, rec apport, and init abund. Runs smoothly with metapopulation example.
=> More features to SIM wrapper

Tag_Integrated_Model/R_wrappers/SIM_TIM_editing.R
working out bugs and more features to the SIMS wrapper.
=> sims wrapper getting better

Managment_Boundaries/HerringPanEM/Operating_Model/MB_OM.dat, Managment_Boundaries/HerringPanEM/Operating_Model/MB_OM.tpl
Fixed a few small errors in the OM that allows data to report for panmictic EM. Herring example.
=> Fixed errors in mismatch to panmictic EM

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
This version can run all matching and also tested with metamictic to panmictic, metamictic to FAA, metamictic to metapop. Lord help me.
=> more mismatches

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
debugging and fine-tuning mismatches. Mostly works.
=> fine tuning mismatches

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Iterative improvements to the diagnostic wrapper. Turning out to be a very useful tool. Can handle many mismatches but still a few more to go.
=> updating wrapper for more mismatches

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
This OM can do everything - Tag design with ALL mismatches. Good luck trying to drive this thing...
=> The OM for the SUPER TIM

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
This wrapper should be smart enough to know what mismatch/match is run and create the correct outputs/plots. There may be some bugs but actively working on it.
=> Diagnostic wrapper for the super TIM

Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_master.R
Checked and debugged for use with all population match/mismatch! Yahoo!
=> Debugged wrapper for super TIM

Tag_Integrated_Model/R_wrappers/SIM_TIM_SIMPLE.R
Made a small change to calls to directories to loop through many folders in the master directory holding scenarios.
=> Small change to code

Tag_Integrated_Model/Estimation_Model/TIM_OM.dat, Tag_Integrated_Model/Estimation_Model/TIM_OM.tpl
Changed the T matrix to be read out by pop and region for all match and mismatch.
=> Fixed T matrix output for smoother mismatch

Tag_Integrated_Model/R_wrappers/SIM_TIM_SIMPLE.R
can run diag code with our without sims or sims with or without diag code
=> Final additions/fixes to simple TIM sims wrapper

Tag_Integrated_Model/R_wrappers/SIM_TIM_PLOTS.R
The SIM_TIM_PLOTS wrapper runs sims, saves data, and generates a number of plots. I have NOT added all the plots I want to yet, but they are coming. The user specifies a number of inputs at the beginning of the code (eg run sims, how many, save values, make plots, run diag code, etc) and the code does the rest. The best part...this WORKS with the mismatch.
=> The master R wrapper...but not done yet!

Tag_Integrated_Model/R_wrappers/SIM_TIM_PLOTS.R
=> Fixed some issues with plotting T

Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
set move_switch ==9 and will implement DD movement that is inversely proportional to relative biomass
=> Allows for inverse DD movement

Management_Boundaries/R_wrappers/SIM_MB_SIMPLE.R
use this wrapper to run the MB code. Runs sims, generates diagnostics and saves results.
=> Adds comparison of misaligned true to est

Management_Boundaries/R_wrappers/SIM_MB_SIMPLE.R
Also, set up to run across folders in a loop.  This has been tested. Generates outputs for true and misaligned areas.
=> Now reports correct comparisons

Tag_Integrated_Model/R_wrappers/SIM_TIM_PLOTS.R
Gradual updates to super TIM simulation wrapper.
=> slowly adding mismatch plots

Tag_Integrated_Model/R_wrappers/SIM_TIM_PLOTS.R
These tables provide true and estimated values for each simulation of an experiment. Can be used to make other plots or diagnose if there is a RNG issue. Also fixed movement plot.
=> Added output of tables used for plotting

Tag_Integrated_Model/R_wrappers/SIM_TIM_PLOTS.R, Tag_Integrated_Model/R_wrappers/TIM_Diagnostics_SIM.R
Fixing some plot titles, etc...OCD stuff
=> Cleaning some things up

Tag_Integrated_Model/Operating_Model/TIM_OM.dat, Tag_Integrated_Model/Operating_Model/TIM_OM.tpl
Updated files with new RNG code
=> Files with fixed RNG

Tag_Integrated_Model/R_wrappers/SIM_TIM_PLOTS.R
Calculates abundance weighted means for F for mismatch to panmictic and other small fixes to plots
=> more plot fixes

Tag_Integrated_Model/R_wrappers/SIM_TIM_PLOTS.R
Fixed a couple errors for metapopulation plots
=> More fixes to mismatch SIMs wrapper

Management_Boundaries/R_wrappers/SIM_MB_SIMPLE.R
Fixed the plot error and added a switch in R code to allow the user to include process error in F and/or Recruitment. Seems to be working just fine now.
=> fixed plot error and added additional features

Tagging Manuscript/Estimation_Model/TIM_EM.tpl, Tagging Manuscript/Figure 1.r, Tagging Manuscript/Figure 2.r, Tagging Manuscript/Operating_Model/TIM_OM.dat, Tagging Manuscript/Operating_Model/TIM_OM.tpl, Tagging Manuscript/SIM_TIM_editing.R, Tagging Manuscript/TIM_Diagnostics_master.R, Tagging Manuscript/manuscript figures.r
improved tagging dynamics with ability to estimate tag mixing and fit tags with unknown age info.
EM has a number of new types of estimated movement options.
wrappers are updated to work with these models.
=> Final tag integrated model (for now)
